del/q data\LdaTrainSet\wb\followers\*
del/q data\LdaTrainSet\wb\followees\*
del/q data\LdaTrainSet\wb\IFMF\*
del/q data\LdaTrainSet\wb\all.CommunityData
del/q data\LdaTrainSet\wb\twMAP
del/q data\LdaResult\all\*
del/q data\LdaResult\wb\IFMF\*
del/q data\GPUResult\all\*
del/q data\keepdata.txt
del/q data\mutualLink.txt
del/q data\testdata.txt